/**
 * Tool contract for Agni SDK.
 *
 * A Tool represents an action that
 * an Agent can execute.
 *
 * Tools contain:
 *
 * - Metadata exposed to the model
 * - Input schema
 * - Execution logic
 *
 * Runtime controls when tools execute.
 */

import type { RunContext } from '../core/run-context.js';

/**
 * Tool metadata exposed to providers.
 */
export interface ToolDefinition {
  /**
   * Unique tool name.
   *
   * Example:
   * "get_weather"
   */
  name: string;

  /**
   * Description shown to the model.
   */
  description: string;

  /**
   * Input schema.
   *
   * Usually JSON Schema.
   *
   * Provider adapters convert
   * this into provider format.
   */
  parameters: unknown;
}

/**
 * Tool execution contract.
 *
 * TInput:
 * Arguments generated by the model.
 *
 * TOutput:
 * Result returned by the tool.
 *
 * TContext:
 * Application runtime context.
 */
export interface Tool<
  TContext = unknown,
  TInput = unknown,
  TOutput = unknown,
> extends ToolDefinition {
  /**
   * Execute tool logic.
   *
   * Runtime provides:
   *
   * - validated input
   * - current execution context
   */
  execute(
    input: TInput,

    context: RunContext<TContext>,
  ): TOutput | Promise<TOutput>;
}
